### PR TITLE
Add functionality to create a new follow-up note

### PR DESCRIPTION
**Pull request by jgru**
Dear Grant, 

this PR adds functionality to create a new follow-up note -- either from the current note or by specifying a certain Luhmann-ID. 
If the following Luhmann ID already exists, the user will be informed about its existence.

Thanks already in advance for considering this addition. 

Best regards,
jgru

### CODE REVIEW

**Comment by localauthor** [comment]
Hey, thanks for this.

As I've noted elsewhere, I'm pretty hesitant to include programmatic numbering like this, since it's not always clear what a proper "follow-up" ID would be. Even in the simplest case, for example, a "follow-up" to "2,8,h" could very well be "2,8,i" or "2,8,h,1". And then, after those IDs exist, a "follow-up" ID cannot really be determined programmatically at all, but must be decided and encoded "by hand."

All that said, the proposed function `zk-luhmann-new-follow-note` seems a bit limited anyway, in that it offers only the former possibility (ie, the next character of the same type) and then errors out if that's not available. It seems that in a lot of cases the function would be a dead-end and manual entry would be necessary anyway.

I've only had a few minutes to try it out, so I'll keep thinking about it. But any thoughts in the meantime?

**Comment by jgru** [comment]
Thanks for you look at it. I see your point, but want to clarify my intention a little: 
I consider a *follow-up-note* to be an increment of the last digit/character. `zk-luhmann-new-follow-up-note` should to just that, e.g. "2,8,h"` -> "2,8,i". I intend to introduce another function called `zk-add-new-branch-note` which will find the next unused branch and insert the note there. The intention behind those two functions is to be a mere helper tool to infer the proper Luhmann-ID in a quick way, it should not replace "reasoning"...maybe this is enough to convince you.

**Comment by localauthor** [comment]
I see, yes. I wonder if instead of insisting on concepts like "follow-up" and "branch" (which don't have clear definitions, and I don't think the package should try to define them) it might be possible to have just `zk-luhmann-new-note` which presents for selection some likely "next" IDs, as well as the possibility to manually enter an ID? I realize that may not be what you have in mind, but that seems like a middle ground between "by hand" and "programmatic."

**Comment by jgru** [comment]
Okay, thanks for getting back to me. 
I'll close this then.

**Pull request closed without merging**
